### ISSUE TITLE
TODO/FIXME Count 4

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-web-authn-token#5]
- [ ] TODO: receive required number of rounds from backend config
       Commit: (be18576) Various fixes to token service and login process.
       File:  [TokenService.js:221](https://github.com/digitalbazaar/bedrock-web-authn-token/blob/master/TokenService.js#L221)
       Dave Longley commented 2 years ago

  - [ ] FIXME account or email?
       Commit: (430f03d) TOTP Updates.
       File:  [TokenService.js:99](https://github.com/digitalbazaar/bedrock-web-authn-token/blob/master/TokenService.js#L99)
       David I. Lehn commented 3 months ago

  - [ ] FIXME: default to hostname?
       Commit: (3030ac1) Add optional serviceId.
       File:  [TokenService.js:55](https://github.com/digitalbazaar/bedrock-web-authn-token/blob/master/TokenService.js#L55)
       David I. Lehn commented 3 months ago

  - [ ] FIXME: there may be better wrappers already created
       Commit: (802f476) Rethrow axios error on `authenticate`.
       File:  [TokenService.js:236](https://github.com/digitalbazaar/bedrock-web-authn-token/blob/master/TokenService.js#L236)
       Dave Longley commented 3 months ago

       TODO Count          1
       FIXME Count         3
       Oldest Comment      2 years ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: receive required number of rounds from backend config

**Comment by dlongley** [comment]
Closing, FIXMEs being removed.
